branches:
  only:
    - master
    - /\d+\.\d+\.\d+/
language: python
python: "2.7"
install: true
script: echo "Nothing to build"
before_deploy:
  - wget -O deploy_addon.py https://gist.githubusercontent.com/olavopeixoto/314f988b0f0f212e8dcce3a0d7af90e1/raw
  - python deploy_addon.py plugin.video.brplay
  - export RELEASE_ZIP=$(ls *.zip)
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: $RELEASE_ZIP
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false